version: "3.8"
services:
  app:
    build:
      context: ./
      dockerfile: infra/Dockerfile
    container_name: app
    working_dir: /app
    volumes:
      - $PWD:/app
    ports:
      - 3010:3000
      - 9992:9992
    command: npm run start:dev
